# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: brand.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='brand.proto',
  package='catalog.brand',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0b\x62rand.proto\x12\rcatalog.brand\"<\n\x0c\x42randMessage\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08isActive\x18\x03 \x01(\x08\x62\x06proto3'
)




_BRANDMESSAGE = _descriptor.Descriptor(
  name='BrandMessage',
  full_name='catalog.brand.BrandMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='catalog.brand.BrandMessage.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='catalog.brand.BrandMessage.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isActive', full_name='catalog.brand.BrandMessage.isActive', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['BrandMessage'] = _BRANDMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BrandMessage = _reflection.GeneratedProtocolMessageType('BrandMessage', (_message.Message,), {
  'DESCRIPTOR' : _BRANDMESSAGE,
  '__module__' : 'brand_pb2'
  # @@protoc_insertion_point(class_scope:catalog.brand.BrandMessage)
  })
_sym_db.RegisterMessage(BrandMessage)


# @@protoc_insertion_point(module_scope)
