get:
  - in: path
    name: configId
    schema:
      type: integer
    required: true
    description:

patch:
  - in: path
    name: configId
    schema:
      type: integer
    required: true
    description:
