# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uom.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='uom.proto',
  package='catalog.uom',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\tuom.proto\x12\x0b\x63\x61talog.uom\"a\n\nUomMessage\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08isActive\x18\x03 \x01(\x08\x12\x13\n\x0b\x64isplayName\x18\x04 \x01(\t\x12\x10\n\x08sellerId\x18\x05 \x01(\rb\x06proto3'
)




_UOMMESSAGE = _descriptor.Descriptor(
  name='UomMessage',
  full_name='catalog.uom.UomMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='catalog.uom.UomMessage.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='catalog.uom.UomMessage.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isActive', full_name='catalog.uom.UomMessage.isActive', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='displayName', full_name='catalog.uom.UomMessage.displayName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sellerId', full_name='catalog.uom.UomMessage.sellerId', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=123,
)

DESCRIPTOR.message_types_by_name['UomMessage'] = _UOMMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UomMessage = _reflection.GeneratedProtocolMessageType('UomMessage', (_message.Message,), {
  'DESCRIPTOR' : _UOMMESSAGE,
  '__module__' : 'uom_pb2'
  # @@protoc_insertion_point(class_scope:catalog.uom.UomMessage)
  })
_sym_db.RegisterMessage(UomMessage)


# @@protoc_insertion_point(module_scope)
