INSERT INTO product_details_v2 (
	sku,
	seller_sku,
	uom_code,
	uom_ratio,
	seller_id,
	seller,
	provider,
	product_line,
	NAME,
	url,
	barcode,
	shipping_types,
	type,
	tax,
	images,
	display_name,
	attribute_set,
	attributes,
	categories,
	seller_categories,
	brand,
	STATUS,
	smart_showroom,
	color,
	seo_info,
	warranty,
	tags,
	is_bundle,
	bundle_products,
	parent_bundles,
	channels,
	attribute_groups,
	product_group,
	terminals,
	manufacture,
	serial_managed,
	serial_generated,
	terminal_groups,
	sku_created_at,
	created_by,
	updated_by 
) SELECT
sku,
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.seller_sku' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.uom_code' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.uom_ratio' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.seller_id' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.seller' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.provider' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.product_line' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.name' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.url' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.barcode' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.shipping_types' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.type' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.tax' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.images' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.display_name' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.attribute_set' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.attributes' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.categories' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.seller_categories' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.brand' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.status' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.smart_showroom' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.color' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.seo_info' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.warranty' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.tags' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.is_bundle' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.bundle_products' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.parent_bundles' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.channels' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.attribute_groups' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.product_group' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.terminals' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.manufacture' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.serial_managed' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.serial_generated' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.terminal_groups' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.sku_created_at' )), 'null' ),
NULLIF( JSON_UNQUOTE( JSON_EXTRACT( DATA, '$.created_by' )), 'null' ),
updated_by
FROM
	product_details 
WHERE
	NOT EXISTS (
	SELECT
		product_details_v2.id 
	FROM
		product_details_v2 
WHERE
	product_details.sku COLLATE utf8mb4_general_ci = product_details_v2.sku COLLATE utf8mb4_general_ci)