get:
  200:
    content:
      application/json:
        schema:
          allOf:
            - $ref: Success.yml
            - type: object
              properties:
                result:
                  type: object
                  properties:
                    detail:
                      type: array
                      items:
                        allOf:
                          - $ref: ../schemas/AttributeSetConfig.yml
                          - type: object
                            properties:
                              fieldDisplay:
                                type: string
  400:
    $ref: ClientErrors.yml#/BadRequest
  500:
    $ref: ServerErrors.yml#/InternalServer

put:
  200:
    content:
      application/json:
        schema:
          allOf:
            - $ref: Success.yml
            - type: object
              properties:
                result:
                  type: object
                  properties:
                    attributeSetConfigs:
                      type: array
                      items:
                        allOf:
                          - $ref: ../schemas/AttributeSetConfig.yml
                          - type: object
                            properties:
                              fieldDisplay:
                                type: string
  400:
    $ref: ClientErrors.yml#/BadRequest
  500:
    $ref: ServerErrors.yml#/InternalServer
