get:
  200:
    content:
      application/json:
        schema:
          allOf:
            - $ref: Success.yml
            - type: object
              properties:
                result:
                  type: object
                  properties:
                    attributeSetName:
                      type: string
                    brandName:
                      type: string
                    isDefault:
                      type: boolean
                    attributes:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          value:
                            type: string
  400:
    $ref: ClientErrors.yml#/BadRequest
  500:
    $ref: ServerErrors.yml#/InternalServer
