# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dto.proto',
  package='catalog.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tdto.proto\x12\ncatalog.v1\"T\n\x10\x41\x64\x64VariantSkuMsg\x12\x1f\n\x0bvariant_sku\x18\x01 \x01(\tR\nvariantSku\x12\x1f\n\x0bsibling_sku\x18\x02 \x01(\tR\nsiblingSku\"\x8e\x01\n\x1cUpdateSkuDimensionsWeightMsg\x12\x10\n\x03sku\x18\x01 \x01(\tR\x03sku\x12\x16\n\x06length\x18\x02 \x01(\x02R\x06length\x12\x14\n\x05width\x18\x03 \x01(\x02R\x05width\x12\x16\n\x06height\x18\x04 \x01(\x02R\x06height\x12\x16\n\x06weight\x18\x05 \x01(\x02R\x06weightb\x06proto3'
)




_ADDVARIANTSKUMSG = _descriptor.Descriptor(
  name='AddVariantSkuMsg',
  full_name='catalog.v1.AddVariantSkuMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='variant_sku', full_name='catalog.v1.AddVariantSkuMsg.variant_sku', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='variantSku', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sibling_sku', full_name='catalog.v1.AddVariantSkuMsg.sibling_sku', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='siblingSku', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=109,
)


_UPDATESKUDIMENSIONSWEIGHTMSG = _descriptor.Descriptor(
  name='UpdateSkuDimensionsWeightMsg',
  full_name='catalog.v1.UpdateSkuDimensionsWeightMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sku', full_name='catalog.v1.UpdateSkuDimensionsWeightMsg.sku', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='sku', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='length', full_name='catalog.v1.UpdateSkuDimensionsWeightMsg.length', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='length', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='width', full_name='catalog.v1.UpdateSkuDimensionsWeightMsg.width', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='width', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='catalog.v1.UpdateSkuDimensionsWeightMsg.height', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='height', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weight', full_name='catalog.v1.UpdateSkuDimensionsWeightMsg.weight', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='weight', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=254,
)

DESCRIPTOR.message_types_by_name['AddVariantSkuMsg'] = _ADDVARIANTSKUMSG
DESCRIPTOR.message_types_by_name['UpdateSkuDimensionsWeightMsg'] = _UPDATESKUDIMENSIONSWEIGHTMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddVariantSkuMsg = _reflection.GeneratedProtocolMessageType('AddVariantSkuMsg', (_message.Message,), {
  'DESCRIPTOR' : _ADDVARIANTSKUMSG,
  '__module__' : 'dto_pb2'
  # @@protoc_insertion_point(class_scope:catalog.v1.AddVariantSkuMsg)
  })
_sym_db.RegisterMessage(AddVariantSkuMsg)

UpdateSkuDimensionsWeightMsg = _reflection.GeneratedProtocolMessageType('UpdateSkuDimensionsWeightMsg', (_message.Message,), {
  'DESCRIPTOR' : _UPDATESKUDIMENSIONSWEIGHTMSG,
  '__module__' : 'dto_pb2'
  # @@protoc_insertion_point(class_scope:catalog.v1.UpdateSkuDimensionsWeightMsg)
  })
_sym_db.RegisterMessage(UpdateSkuDimensionsWeightMsg)


# @@protoc_insertion_point(module_scope)
