put:
  content:
    application/json:
      schema:
        type: array
        items:
          type: object
          properties:
            fieldDisplay:
              type: string
            detail:
              type: array
              items:
                $ref: ../schemas/AttributeSetConfig.yml
