"""Migrate product_details_v2

Revision ID: 01e11fb14861
Revises: f99b52ecbca7
Create Date: 2021-07-29 08:47:10.254486

"""
import os
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import mysql
from catalog import config

# revision identifiers, used by Alembic.
revision = '01e11fb14861'
down_revision = 'f99b52ecbca7'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###