"""empty message

Revision ID: 039bb958de05
Revises: 4328a910c40f
Create Date: 2022-05-12 08:36:18.096387

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '039bb958de05'
down_revision = '4328a910c40f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_adult', sa.Boolean(), nullable=False))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'is_adult')

