"""Migrate product_details_v2

Revision ID: 05c139f98888
Revises: 1ae38a9c207a
Create Date: 2021-07-26 15:39:20.138552

"""
import os
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import mysql
from catalog import config

# revision identifiers, used by Alembic.
revision = '05c139f98888'
down_revision = '1ae38a9c207a'
branch_labels = None
depends_on = None


def upgrade():
    return
    # ### commands auto generated by Alembic - please adjust! ###
    # with open(os.path.join(config.ROOT_DIR, 'catalog', 'utils', 'MIGRATE_PRODUCT_DETAILS_V2.sql'), 'r') as file:
    #     sql = file.read()
    #     op.execute(text(sql))
    # # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
