"""empty message

Revision ID: 0f9f198cc9e8
Revises: 78c372da0766
Create Date: 2020-05-19 14:40:20.877776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f9f198cc9e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('object', sa.String(length=255), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('object_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amqp_messages',
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.String(length=255), nullable=False),
    sa.Column('routing_key', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('attribute_set_id', sa.Integer(), nullable=False),
    sa.Column('send_by', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribute_sets',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brands',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('doc_request', sa.Integer(), nullable=True),
    sa.Column('approved_status', sa.Integer(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('internal_code', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('colors',
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('editing_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('can_moved_status', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editing_status_code'), 'editing_status', ['code'], unique=False)
    op.create_table('file_cloud',
    sa.Column('public_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_imports',
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('success_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('total_row', sa.Integer(), nullable=True),
    sa.Column('total_row_success', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('attribute_set_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_edit_product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('updated_by_email', sa.String(length=255), nullable=True),
    sa.Column('updated_by_name', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_edit_product_configurable',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('configurable_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs_import_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('name_file', sa.String(length=255), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exchange', sa.String(length=255), nullable=True),
    sa.Column('queue', sa.String(length=255), nullable=True),
    sa.Column('routing_key', sa.String(length=128), nullable=True),
    sa.Column('body_raw', sa.TEXT(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('log', sa.TEXT(), nullable=True),
    sa.Column('properties', sa.TEXT(), nullable=True),
    sa.Column('status', sa.Enum('init', 'ok', 'failed', 'retried', 'cancelled', 'ignored', name='status'), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_logs_routing_key'), 'message_logs', ['routing_key'], unique=False)
    op.create_table('misc',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=101), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_misc_code'), 'misc', ['code'], unique=False)
    op.create_table('product_details',
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('catalog_status_code', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_srm_request',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('is_send', sa.Integer(), nullable=True),
    sa.Column('last_sent', sa.TIMESTAMP(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('product_units',
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('product_status',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('code', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_status_code'), 'product_status', ['code'], unique=False)

    op.create_table('providers',
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_categories',
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['sale_categories.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sellable_product_tags',
    sa.Column('sellable_product_id', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('manual_sku', sa.Boolean(), nullable=True),
    sa.Column('is_manage_price', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sellers_terminals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('terminal_id', sa.Integer(), nullable=True),
    sa.Column('is_requested_approval', sa.Boolean(), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('selling_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('config', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('srm_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('selling_status', sa.Integer(), nullable=False),
    sa.Column('selling_status_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taxes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('units',
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribute_groups',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('is_flat', sa.Boolean(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('system_group', sa.Boolean(), nullable=True),
    sa.Column('attribute_set_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attribute_set_id'], ['attribute_sets.id'], name='FK_attribute_groups_attribute_set_id', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribute_set_config',
    sa.Column('is_default', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.Column('attribute_1_id', sa.Integer(), nullable=True),
    sa.Column('attribute_1_value', sa.Integer(), nullable=True),
    sa.Column('attribute_2_id', sa.Integer(), nullable=True),
    sa.Column('attribute_2_value', sa.Integer(), nullable=True),
    sa.Column('attribute_3_id', sa.Integer(), nullable=True),
    sa.Column('attribute_3_value', sa.Integer(), nullable=True),
    sa.Column('attribute_4_id', sa.Integer(), nullable=True),
    sa.Column('attribute_4_value', sa.Integer(), nullable=True),
    sa.Column('attribute_5_id', sa.Integer(), nullable=True),
    sa.Column('attribute_5_value', sa.Integer(), nullable=True),
    sa.Column('attribute_set_id', sa.Integer(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attribute_set_id'], ['attribute_sets.id'], name='fk_attribute_set_config_attribute_sets', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attributes',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('value_type', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Integer(), nullable=True),
    sa.Column('is_comparable', sa.Integer(), nullable=True),
    sa.Column('is_searchable', sa.Integer(), nullable=True),
    sa.Column('is_filterable', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['product_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('tax_in_code', sa.String(length=10), nullable=False),
    sa.Column('tax_out_code', sa.String(length=10), nullable=False),
    sa.Column('manage_serial', sa.Boolean(), nullable=False),
    sa.Column('auto_generate_serial', sa.Boolean(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('attribute_set_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attribute_set_id'], ['attribute_sets.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('iam_users',
    sa.Column('iam_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('master_categories',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('manage_serial', sa.Boolean(), nullable=True),
    sa.Column('auto_generate_serial', sa.Boolean(), nullable=True),
    sa.Column('attribute_set_id', sa.Integer(), nullable=True),
    sa.Column('tax_in_code', sa.String(length=10), nullable=True),
    sa.Column('tax_out_code', sa.String(length=10), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attribute_set_id'], ['attribute_sets.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['master_categories.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )

    
    op.create_table('product_labels',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('code', sa.String(length=255), nullable=False),
        sa.Column('status', sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(['status'], ['product_status.code'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('terminals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('full_address', sa.String(length=511), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_requested_approval', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
   
    op.create_table('attribute_description',
    sa.Column('short_description_priority', sa.Integer(), nullable=True),
    sa.Column('short_description_before', sa.String(length=255), nullable=True),
    sa.Column('short_description_after', sa.String(length=255), nullable=True),
    sa.Column('short_description_default', sa.Text(), nullable=True),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name='FK_attribute_description__attribute_id', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribute_group_attribute',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('highlight', sa.Integer(), nullable=True),
    sa.Column('text_before', sa.Text(), nullable=True),
    sa.Column('text_after', sa.Text(), nullable=True),
    sa.Column('is_displayed', sa.Integer(), nullable=True),
    sa.Column('is_variation', sa.Integer(), nullable=True),
    sa.Column('variation_display_type', sa.Text(length=255), nullable=True),
    sa.Column('variation_priority', sa.Integer(), nullable=True),
    sa.Column('attribute_group_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attribute_group_id'], ['attribute_groups.id'], name='FK_attribute_group_attribute__attribute_group_id', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name='FK_attribute_group_attribute__attribute_id', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribute_options',
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name='FK_attribute_option__attribute_id', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['product_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribute_set_config_detail',
    sa.Column('attribute_set_config_id', sa.Integer(), nullable=True),
    sa.Column('field_display', sa.String(length=255), nullable=True),
    sa.Column('object_type', sa.String(length=255), nullable=True),
    sa.Column('object_value', sa.String(length=255), nullable=True),
    sa.Column('text_before', sa.String(length=255), nullable=True),
    sa.Column('text_after', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attribute_set_config_id'], ['attribute_set_config.id'], name='fk_attribute_set_config_detail_attribute_set_config', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('products',
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('is_bundle', sa.Boolean(), nullable=True),
        sa.Column('display_name', sa.String(length=255), nullable=True),
        sa.Column('short_name', sa.String(length=255), nullable=True),
        sa.Column('model', sa.String(length=255), nullable=True),
        sa.Column('type', sa.String(length=30), nullable=True),
        sa.Column('is_physical', sa.Boolean(), nullable=True),
        sa.Column('url_key', sa.String(length=100), nullable=True),
        sa.Column('spu', sa.Integer(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('detailed_description', sa.Text(), nullable=True),
        sa.Column('warranty_months', sa.Integer(), nullable=True),
        sa.Column('warranty_note', sa.String(length=255), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('updated_by', sa.Integer(), nullable=True),
        sa.Column('attribute_set_id', sa.Integer(), nullable=True),
        sa.Column('category_id', sa.Integer(), nullable=True),
        sa.Column('master_category_id', sa.Integer(), nullable=True),
        sa.Column('brand_id', sa.Integer(), nullable=False),
        sa.Column('tax_in_code', sa.String(length=10), nullable=True),
        sa.Column('tax_out_code', sa.String(length=10), nullable=True),
        sa.Column('unit_id', sa.Integer(), nullable=False),
        sa.Column('unit_po_id', sa.Integer(), nullable=True),
        sa.Column('editing_status_code', sa.String(length=30), nullable=False),
        sa.Column('default_variant_id', sa.Integer(), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        # sa.ForeignKeyConstraint(['attribute_set_id'], ['attribute_sets.id'], ),
        # sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name='FK_products__brand_id',
        #                         onupdate='CASCADE', ondelete='RESTRICT'),
        # sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        # sa.ForeignKeyConstraint(['default_variant_id'], ['product_variants.id'], ),
        # sa.ForeignKeyConstraint(['editing_status_code'], ['editing_status.code'], ),
        # sa.ForeignKeyConstraint(['master_category_id'], ['master_categories.id'],
        #                         name='FK_products__master_category_id', onupdate='CASCADE',
        #                         ondelete='RESTRICT'),
        # sa.ForeignKeyConstraint(['tax_in_code'], ['taxes.code'], ),
        # sa.ForeignKeyConstraint(['tax_out_code'], ['taxes.code'], ),
        # sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name='FK_products_unit_id', onupdate='CASCADE',
        #                         ondelete='RESTRICT'),
        # sa.ForeignKeyConstraint(['unit_po_id'], ['units.id'], name='FK_products_unit_po_id',
        #                         onupdate='CASCADE', ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('spu')
    )

    op.create_table('product_variants',
        sa.Column('product_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.Text(), nullable=True),
        sa.Column('code', sa.String(length=255), nullable=True),
        sa.Column('url_key', sa.Text(), nullable=True),
        sa.Column('created_by', sa.String(length=255), nullable=True),
        sa.Column('updated_by', sa.String(length=255), nullable=True),
        sa.Column('editing_status_code', sa.String(length=255), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        # sa.ForeignKeyConstraint(['editing_status_code'], ['editing_status.code'], ),
        # sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('variant_images',
        sa.Column('name', sa.Text(), nullable=True),
        sa.Column('url', sa.Text(), nullable=True),
        sa.Column('path', sa.Text(), nullable=True),
        sa.Column('label', sa.String(length=255), nullable=True),
        sa.Column('priority', sa.Integer(), nullable=False),
        sa.Column('is_displayed', sa.Integer(), nullable=True),
        sa.Column('status', sa.Integer(), nullable=True),
        sa.Column('product_variant_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name='FK_variant_images__product_id', onupdate='CASCADE', ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('variant_attribute',
        sa.Column('value', sa.Text(), nullable=False),
        sa.Column('variant_id', sa.Integer(), nullable=False),
        sa.Column('attribute_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
        sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('product_attribute',
        sa.Column('value', sa.Text(), nullable=True),
        sa.Column('product_id', sa.Integer(), nullable=True),
        sa.Column('attribute_id', sa.Integer(), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name='FK_product_attribute__attribute_id', onupdate='CASCADE', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='FK_product_attribute__product_id', onupdate='CASCADE', ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('sellable_products',
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('sku', sa.String(length=100), nullable=False),
        sa.Column('barcode', sa.String(length=50), nullable=True),
        sa.Column('warranty_months', sa.Integer(), nullable=False),
        sa.Column('warranty_note', sa.String(length=255), nullable=True),
        sa.Column('label', sa.String(length=255), nullable=True),
        sa.Column('is_bundle', sa.Boolean(), nullable=False),
        sa.Column('status', sa.String(length=255), nullable=True),
        sa.Column('supplier_sale_price', sa.Integer(), nullable=True),
        sa.Column('sale_price', sa.Integer(), nullable=True),
        sa.Column('model', sa.String(length=255), nullable=True),
        sa.Column('created_by', sa.String(length=255), nullable=True),
        sa.Column('allow_selling_without_stock', sa.Boolean(), nullable=True),
        sa.Column('manage_serial', sa.Boolean(), nullable=True),
        sa.Column('auto_generate_serial', sa.Boolean(), nullable=True),
        sa.Column('part_number', sa.String(length=255), nullable=True),
        sa.Column('comment', sa.String(length=255), nullable=True),
        sa.Column('product_type', sa.String(length=255), nullable=True),
        sa.Column('expiry_tracking', sa.Boolean(), nullable=True),
        sa.Column('expiration_type', sa.Integer(), nullable=True),
        sa.Column('days_before_exp_lock', sa.Integer(), nullable=True),
        sa.Column('objective', sa.String(length=255), nullable=True),
        sa.Column('tax_in_code', sa.String(length=10), nullable=True),
        sa.Column('tax_out_code', sa.String(length=10), nullable=True),
        sa.Column('brand_id', sa.Integer(), nullable=True),
        sa.Column('category_id', sa.Integer(), nullable=True),
        sa.Column('attribute_set_id', sa.Integer(), nullable=True),
        sa.Column('unit_id', sa.Integer(), nullable=True),
        sa.Column('unit_po_id', sa.Integer(), nullable=True),
        sa.Column('color_id', sa.Integer(), nullable=True),
        sa.Column('variant_id', sa.Integer(), nullable=False),
        sa.Column('editing_status_code', sa.String(length=20), nullable=False),
        sa.Column('selling_status_code', sa.String(length=20), nullable=True),
        sa.Column('seller_id', sa.Integer(), nullable=False),
        sa.Column('provider_id', sa.Integer(), nullable=True),
        sa.Column('product_id', sa.Integer(), nullable=True),
        sa.Column('master_category_id', sa.Integer(), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        # sa.ForeignKeyConstraint(['attribute_set_id'], ['attribute_sets.id'], ),
        # sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
        # sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        # sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
        # sa.ForeignKeyConstraint(['editing_status_code'], ['editing_status.code'], ),
        # sa.ForeignKeyConstraint(['master_category_id'], ['master_categories.id'], name='FK_sellable_products__master_category_id', onupdate='CASCADE', ondelete='RESTRICT'),
        # sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
        # sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
        # sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
        # sa.ForeignKeyConstraint(['selling_status_code'], ['misc.code'], ),
        # sa.ForeignKeyConstraint(['tax_in_code'], ['taxes.code'], ),
        # sa.ForeignKeyConstraint(['tax_out_code'], ['taxes.code'], ),
        # sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
        # sa.ForeignKeyConstraint(['unit_po_id'], ['units.id'], ),
        # sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('attachments',
        sa.Column('url', sa.Text(), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('sellable_product_id', sa.Integer(), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['sellable_product_id'], ['sellable_products.id'], name='FK_attachments__sellable_products', onupdate='CASCADE', ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sellable_product_bundles',
        sa.Column('bundle_id', sa.Integer(), nullable=True),
        sa.Column('sellable_product_id', sa.Integer(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['bundle_id'], ['sellable_products.id'], ),
        sa.ForeignKeyConstraint(['sellable_product_id'], ['sellable_products.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sellable_product_seo_info',
        sa.Column('sellable_product_id', sa.Integer(), nullable=True),
        sa.Column('short_description', sa.Text(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('meta_title', sa.Text(), nullable=True),
        sa.Column('meta_keyword', sa.Text(), nullable=True),
        sa.Column('meta_description', sa.Text(), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['sellable_product_id'], ['sellable_products.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sellable_product_seo_info_terminal',
        sa.Column('sellable_product_id', sa.Integer(), nullable=False),
        sa.Column('terminal_id', sa.Integer(), nullable=False),
        sa.Column('terminal_code', sa.String(length=45), nullable=True),
        sa.Column('display_name', sa.String(length=255), nullable=True),
        sa.Column('meta_title', sa.Text(), nullable=True),
        sa.Column('meta_keyword', sa.Text(), nullable=True),
        sa.Column('meta_description', sa.Text(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('short_description', sa.Text(), nullable=True),
        sa.Column('created_by', sa.String(length=255), nullable=True),
        sa.Column('updated_by', sa.String(length=255), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['sellable_product_id'], ['sellable_products.id'], ),
        sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('terminal_id', 'sellable_product_id')
    )

    op.create_table('sellable_product_terminal',
        sa.Column('sellable_product_id', sa.Integer(), nullable=False),
        sa.Column('terminal_id', sa.Integer(), nullable=False),
        sa.Column('terminal_code', sa.String(length=255), nullable=True),
        sa.Column('terminal_type', sa.String(length=255), nullable=True),
        sa.Column('meta_title', sa.Text(), nullable=True),
        sa.Column('meta_keyword', sa.Text(), nullable=True),
        sa.Column('meta_description', sa.Text(), nullable=True),
        sa.Column('created_by', sa.String(length=100), nullable=True),
        sa.Column('updated_by', sa.String(length=100), nullable=True),
        sa.Column('apply_seller_id', sa.Integer(), nullable=True),
        sa.Column('on_off_status', sa.String(length=45), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['sellable_product_id'], ['sellable_products.id'], ),
        sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('terminal_id', 'sellable_product_id')
    )

    op.create_table('editing_status_histories',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('editing_status', sa.String(length=255), nullable=True),
        sa.Column('state', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('created_by', sa.String(length=20), nullable=True),
        sa.Column('comment', sa.String(length=255), nullable=True),
        sa.Column('reason_type', sa.String(length=255), nullable=True),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='FK_editing_status_history_product_id', onupdate='CASCADE', ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_foreign_key(None, 'products', 'attribute_sets', ['attribute_set_id'], ['id'], )
    op.create_foreign_key('FK_products__brand_id', 'products', 'brands', ['brand_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'],)
    op.create_foreign_key(None, 'products', 'product_variants', ['default_variant_id'], ['id'], )
    op.create_foreign_key(None, 'products', 'editing_status', ['editing_status_code'], ['code'], )
    op.create_foreign_key('FK_products__master_category_id', 'products', 'master_categories', ['master_category_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'products', 'taxes', ['tax_in_code'], ['code'], )
    op.create_foreign_key('FK_products_unit_id', 'products', 'units', ['unit_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key('FK_products_unit_po_id', 'products', 'units', ['unit_po_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')

    op.create_foreign_key(None, 'product_variants', 'editing_status', ['editing_status_code'], ['code'], )
    op.create_foreign_key(None, 'product_variants', 'products', ['product_id'], ['id'], )

    op.create_foreign_key(None, 'sellable_products', 'attribute_sets', ['attribute_set_id'], ['id'], )
    op.create_foreign_key(None, 'sellable_products', 'brands', ['brand_id'], ['id'], )
    op.create_foreign_key(None, 'sellable_products', 'categories', ['category_id'], ['id'], )
    op.create_foreign_key(None, 'sellable_products', 'colors', ['color_id'], ['id'], )
    op.create_foreign_key(None, 'sellable_products', 'editing_status', ['editing_status_code'], ['code'], )
    op.create_foreign_key('FK_sellable_products__master_category_id', 'sellable_products', 'master_categories', ['master_category_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'sellable_products', 'products', ['product_id'], ['id'], )
    op.create_foreign_key(None, 'sellable_products', 'providers', ['provider_id'], ['id'], )
    op.create_foreign_key(None, 'sellable_products', 'sellers', ['seller_id'], ['id'], )
    op.create_foreign_key(None, 'sellable_products', 'misc', ['selling_status_code'], ['code'], )
    op.create_foreign_key(None, 'sellable_products', 'taxes', ['tax_in_code'], ['code'], )
    op.create_foreign_key(None, 'sellable_products', 'taxes', ['tax_out_code'], ['code'], )
    op.create_foreign_key(None, 'sellable_products', 'units', ['unit_id'], ['id'], )
    op.create_foreign_key(None, 'sellable_products', 'units', ['unit_po_id'], ['id'], )
    op.create_foreign_key(None, 'sellable_products', 'product_variants', ['variant_id'], ['id'], )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sellable_product_terminal')
    op.drop_table('sellable_product_seo_info_terminal')
    op.drop_table('sellable_product_seo_info')
    op.drop_table('sellable_product_bundles')
    op.drop_table('attachments')
    op.drop_table('variant_attribute')
    op.drop_table('sellable_products')
    op.drop_table('product_attribute')
    op.drop_table('attribute_set_config_detail')
    op.drop_table('attribute_options')
    op.drop_table('attribute_group_attribute')
    op.drop_table('attribute_description')
    op.drop_table('variant_images')
    op.drop_table('users')
    op.drop_table('terminals')
    op.drop_table('product_labels')
    op.drop_table('master_categories')
    op.drop_table('iam_users')
    op.drop_table('editing_status_histories')
    op.drop_table('categories')
    op.drop_table('attributes')
    op.drop_table('attribute_set_config')
    op.drop_table('attribute_groups')
    op.drop_table('units')
    op.drop_table('taxes')
    op.drop_table('srm_status')
    op.drop_table('selling_status')
    op.drop_table('sellers_terminals')
    op.drop_table('sellers')
    op.drop_table('sellable_product_tags')
    op.drop_table('sale_categories')
    op.drop_table('providers')
    op.drop_table('products')
    op.drop_table('product_variants')
    op.drop_table('product_units')
    op.drop_table('product_status')
    op.drop_table('product_srm_request')
    op.drop_table('product_details')
    op.drop_table('misc')
    op.drop_index(op.f('ix_message_logs_routing_key'), table_name='message_logs')
    op.drop_table('message_logs')
    op.drop_table('logs_import_file')
    op.drop_table('log_edit_product_configurable')
    op.drop_table('log_edit_product')
    op.drop_table('files')
    op.drop_table('file_imports')
    op.drop_table('file_cloud')
    op.drop_table('editing_status')
    op.drop_table('colors')
    op.drop_table('brands')
    op.drop_table('attribute_sets')
    op.drop_table('amqp_messages')
    op.drop_table('action_logs')
    # ### end Alembic commands ###
