"""empty message

Revision ID: 125ff42a4216
Revises: b3313d8626b2
Create Date: 2022-01-06 13:44:28.949483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
import catalog

revision = '125ff42a4216'
down_revision = 'b3313d8626b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', catalog.models.base.BaseTimestamp(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', catalog.models.base.BaseTimestamp(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('product_categories__category_id', 'product_categories', ['category_id'], unique=False)
    op.create_index('product_categories__product_id', 'product_categories', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('product_categories__product_id', table_name='product_categories')
    op.drop_index('product_categories__category_id', table_name='product_categories')
    op.drop_table('product_categories')
    # ### end Alembic commands ###
