"""empty message

Revision ID: 13647ed6ef86
Revises: 039bb958de05
Create Date: 2022-07-21 14:58:13.654251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13647ed6ef86'
down_revision = '039bb958de05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('meta_title', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('meta_description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('meta_keyword', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'meta_keyword')
    op.drop_column('products', 'meta_description')
    op.drop_column('products', 'meta_title')
    # ### end Alembic commands ###
