"""add_created_from_column_for_sellable_product_shipping_type_table

Revision ID: 19b3d9857ae8
Revises: 4ced24dfa533
Create Date: 2021-04-05 14:12:30.420983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19b3d9857ae8'
down_revision = '4ced24dfa533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellable_product_shipping_type', sa.Column('created_from', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellable_product_shipping_type', 'created_from')
    # ### end Alembic commands ###
