"""Add default for shipping type

Revision ID: 1bb79b45d80c
Revises: 4c12ffae73c3
Create Date: 2021-06-16 16:29:19.435826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = '1bb79b45d80c'
down_revision = '4c12ffae73c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipping_types', sa.Column('is_default', sa.Boolean(), nullable=True))
    op.execute(text('''
        INSERT INTO `shipping_types`(code, name, is_active, is_default, created_by, updated_by, created_at, updated_at) 
        VALUES ('NORMAL', 'Hàng thông thường', 1, 1, 'Catalog', 'Catalog', '2021-06-16 09:30:54', '2021-06-16 09:30:54');
    '''))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipping_types', 'is_default')
    # ### end Alembic commands ###
