"""empty message

Revision ID: 28e21abb971e
Revises: 85bc1c3b2d1d
Create Date: 2020-06-09 15:24:06.070618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
from sqlalchemy.orm import sessionmaker

revision = '28e21abb971e'
down_revision = '85bc1c3b2d1d'
branch_labels = None
depends_on = None

Session = sessionmaker()

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('product_logs',
                    sa.Column('updated_by', sa.String(length=255), nullable=True),
                    sa.Column('sku', sa.String(length=100), nullable=False),
                    sa.Column('old_data', sa.Text(), nullable=True),
                    sa.Column('new_data', sa.Text(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_logs')
    # ### end Alembic commands ###
