"""empty message

Revision ID: 4ced24dfa533
Revises: d91ff0ff5b31
Create Date: 2021-03-31 15:01:49.043318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ced24dfa533'
down_revision = 'd91ff0ff5b31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sellable_product_shipping_type',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, primary_key=True),
        sa.Column('sellable_product_id', sa.Integer(), nullable=False, index=True),
        sa.Column('shipping_type_id', sa.Integer(), nullable=False, index=True),
        sa.Column('created_by', sa.String(length=255), nullable=True),
        sa.Column('updated_by', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(),
                  server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
                  nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sellable_product_shipping_type')
    # ### end Alembic commands ###
