"""empty message

Revision ID: 59eb5cc91f63
Revises: 5d8ef2c6a429
Create Date: 2020-07-06 10:41:55.762990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59eb5cc91f63'
down_revision = '5d8ef2c6a429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('product_logs', 'old_data',
               existing_type=mysql.TEXT(),
               type_=mysql.LONGTEXT()
                    )
    op.alter_column('product_logs', 'new_data',
                    existing_type=mysql.TEXT(),
                    type_=mysql.LONGTEXT()
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
