"""empty message

Revision ID: 62becc0611aa
Revises: 59eb5cc91f63
Create Date: 2020-07-07 15:41:14.022233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62becc0611aa'
down_revision = '59eb5cc91f63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('sellable_product_tags', 'tags',
               existing_type=mysql.VARCHAR(255),
               type_=mysql.TEXT()
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
