"""empty message

Revision ID: 85bc1c3b2d1d
Revises: e1903625ca83
Create Date: 2020-06-09 10:43:43.809774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85bc1c3b2d1d'
down_revision = '9e5799580d8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_details', sa.Column('updated_by', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=True,
                            comment='Nguoi cuoi cung update du lieu'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_details', 'updated_by')
    # ### end Alembic commands ###
