"""Add product_details_v2 table

Revision ID: 97884ae7c732
Revises: dad50b349ddc
Create Date: 2021-07-06 08:49:11.173433

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97884ae7c732'
down_revision = 'dad50b349ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_details_v2',
                    sa.Column('sku', sa.String(length=255), nullable=True),
                    sa.Column('seller_sku', sa.String(length=255), nullable=True),
                    sa.Column('uom_code', sa.String(length=255), nullable=True),
                    sa.Column('uom_ratio', sa.Float(), nullable=True),
                    sa.Column('seller_id', sa.Integer(), nullable=True),
                    sa.Column('seller', sa.Text(), nullable=True),
                    sa.Column('provider', sa.Text(), nullable=True),
                    sa.Column('product_line', sa.Text(), nullable=True),
                    sa.Column('name', sa.String(length=500), nullable=True),
                    sa.Column('url', sa.String(length=255), nullable=True),
                    sa.Column('barcode', sa.String(length=255), nullable=True),
                    sa.Column('shipping_types', sa.String(length=500), nullable=True),
                    sa.Column('type', sa.String(length=255), nullable=True),
                    sa.Column('tax', sa.String(length=1000), nullable=True),
                    sa.Column('images', sa.Text(), nullable=True),
                    sa.Column('display_name', sa.String(length=255), nullable=True),
                    sa.Column('attribute_set', sa.String(length=255), nullable=True),
                    sa.Column('attributes', mysql.LONGTEXT(), nullable=True),
                    sa.Column('categories', sa.Text(), nullable=True),
                    sa.Column('seller_categories', sa.Text(), nullable=True),
                    sa.Column('brand', sa.String(length=1000), nullable=True),
                    sa.Column('status', sa.String(length=1000), nullable=True),
                    sa.Column('smart_showroom', sa.String(length=1000), nullable=True),
                    sa.Column('color', sa.Text(), nullable=True),
                    sa.Column('seo_info', mysql.LONGTEXT(), nullable=True),
                    sa.Column('warranty', sa.String(length=1000), nullable=True),
                    sa.Column('tags', sa.String(length=1000), nullable=True),
                    sa.Column('is_bundle', sa.Boolean(), nullable=True),
                    sa.Column('bundle_products', sa.Text(), nullable=True),
                    sa.Column('parent_bundles', sa.Text(), nullable=True),
                    sa.Column('channels', sa.Text(), nullable=True),
                    sa.Column('attribute_groups', mysql.LONGTEXT(), nullable=True),
                    sa.Column('product_group', mysql.LONGTEXT(), nullable=True),
                    sa.Column('terminals', sa.Text(), nullable=True),
                    sa.Column('manufacturer', sa.Text(), nullable=True),
                    sa.Column('serial_managed', sa.Boolean(), nullable=True),
                    sa.Column('serial_generated', sa.Boolean(), nullable=True),
                    sa.Column('terminal_groups', sa.String(length=1000), nullable=True),
                    sa.Column('created_by', sa.String(length=255), nullable=True),
                    sa.Column('updated_by', sa.String(length=255), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('IDX_product_details_v2__seller_sku', 'product_details_v2', ['seller_sku'], unique=False)
    op.create_index('IDX_product_details_v2__sku', 'product_details_v2', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('IDX_product_details_v2__sku', table_name='product_details_v2')
    op.drop_index('IDX_product_details_v2__seller_sku', table_name='product_details_v2')
    op.drop_table('product_details_v2')
    # ### end Alembic commands ###
