"""migrate product_details_v2

Revision ID: 9c08e0e87c20
Revises: c5bce7eb6a0b
Create Date: 2021-08-06 15:11:42.330362

"""
import os
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import mysql
from catalog import config


# revision identifiers, used by Alembic.
revision = '9c08e0e87c20'
down_revision = 'c5bce7eb6a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
