"""Add platform_sellers table

Revision ID: addcbc8b6c5f
Revises: 125ff42a4216
Create Date: 2022-01-13 14:37:53.912785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'addcbc8b6c5f'
down_revision = '125ff42a4216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_sellers',
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('platform_sellers__platform_id', 'platform_sellers', ['platform_id'], unique=False)
    op.create_index('platform_sellers__seller_id', 'platform_sellers', ['seller_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('platform_sellers__seller_id', table_name='platform_sellers')
    op.drop_index('platform_sellers__platform_id', table_name='platform_sellers')
    op.drop_table('platform_sellers')
    # ### end Alembic commands ###
