"""Add platform to import table

Revision ID: b339981631a9
Revises: d4573ee220fe
Create Date: 2022-01-12 16:57:57.504300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.orm import Session

# revision identifiers, used by Alembic.
revision = 'b339981631a9'
down_revision = 'd4573ee220fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('file_imports', sa.Column('platform_id', sa.Integer(), nullable=True))
    bind = op.get_bind()
    session = Session(bind=bind)
    session.execute(
        text(
            """
            INSERT INTO misc (`name`, `type`, `code`, `config`) 
            VALUES 
            ('Cập nhật danh mục của sàn cho sản phẩm', 'import_type', 'upsert_product_category', :config)
            """
        ), {
            "config": '{"version":1}'
        }
    )
    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    bind = op.get_bind()
    session = Session(bind=bind)
    update_misc_sql = """
                        DELETE FROM misc WHERE `type` = 'import_type' AND `code` = 'upsert_product_category'
                        """
    session.execute(update_misc_sql)
    session.commit()
    op.drop_column('file_imports', 'platform_id')
    # ### end Alembic commands ###
