"""create table sellable_product_barcodes

Revision ID: b8e27c42e830
Revises: 0580dfad764a
Create Date: 2021-08-30 20:42:51.920249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8e27c42e830'
down_revision = '0580dfad764a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellable_product_barcodes',
    sa.Column('sellable_product_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('sellable_product_barcodes__sku_id', 'sellable_product_barcodes', ['sellable_product_id'], unique=False)
    op.create_index('sellable_product_barcodes__barcode', 'sellable_product_barcodes', ['barcode'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('sellable_product_barcodes__barcode', table_name='sellable_product_barcodes')
    op.drop_index('sellable_product_barcodes__sku_id', table_name='sellable_product_barcodes')
    op.drop_table('sellable_product_barcodes')
    # ### end Alembic commands ###
