"""add seller_id to units

Revision ID: c3d18b3dec07
Revises: 1bb79b45d80c
Create Date: 2021-06-16 16:21:54.119434

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3d18b3dec07'
down_revision = '1bb79b45d80c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(
        text(
            """
                ALTER TABLE units ADD seller_id int NOT NULL DEFAULT 0
            """
        )
    )
    conn.execute(
        text(
            """
                ALTER TABLE units ADD display_name nvarchar(255) NULL
            """
        )
    )
    conn.execute(
        text(
            """
                ALTER TABLE attribute_options ADD display_value nvarchar(255) NULL
            """
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(
        text(
            """
                ALTER TABLE units DROP COLUMN seller_id
            """
        )
    )
    conn.execute(
        text(
            """
                ALTER TABLE units DROP COLUMN display_name
            """
        )
    )
    conn.execute(
        text(
            """
                ALTER TABLE attribute_options DROP COLUMN display_value
            """
        )
    )
    # ### end Alembic commands ###
