"""add field to product_details_v2

Revision ID: c5bce7eb6a0b
Revises: 01e11fb14861
Create Date: 2021-08-06 12:59:56.399575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c5bce7eb6a0b'
down_revision = '01e11fb14861'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('product_details_v2', sa.Column('sku_created_at', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_details_v2', 'sku_created_at')
    # ### end Alembic commands ###
