"""Add url_key to sellable_product_seo_info_terminal table

Revision ID: c886d6d67f29
Revises: e3e99e2ff1b1
Create Date: 2021-03-16 17:44:03.151062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c886d6d67f29'
down_revision = 'e3e99e2ff1b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellable_product_seo_info_terminal', sa.Column('url_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellable_product_seo_info_terminal', 'url_key')
    # ### end Alembic commands ###
