"""Add platform_categories to product_details_v2 table

Revision ID: d4573ee220fe
Revises: addcbc8b6c5f
Create Date: 2022-01-14 09:11:09.488290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd4573ee220fe'
down_revision = 'addcbc8b6c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('product_details_v2', sa.Column('platform_categories', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_details_v2', 'platform_categories')
    # ### end Alembic commands ###
