"""Add thumbnail_url to attribute_options

Revision ID: db0725a93d87
Revises: 463e5dbca927
Create Date: 2021-09-22 20:02:32.674658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db0725a93d87'
down_revision = '463e5dbca927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute_options', sa.Column('thumbnail_url', sa.String(255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attribute_options', 'thumbnail_url')
    # ### end Alembic commands ###
