"""empty message

Revision ID: e04b8a0bc03b
Revises: 371981f4c891
Create Date: 2020-07-20 02:25:59.142247

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from sqlalchemy import func

revision = 'e04b8a0bc03b'
down_revision = '371981f4c891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_policy',
                    sa.Column('id', sa.Integer(), autoincrement=True,nullable=False),
                    sa.Column('shipping_type', sa.String(255), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(),
                              server_default=func.now(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(),
                              server_default=func.now(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('shipping_policy_mapping',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('policy_id', sa.Integer(), nullable=False),
                    sa.Column('provider_id', sa.Integer(), nullable=False),
                    sa.Column('category_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(),
                              server_default=func.now(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(),
                              server_default=func.now(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipping_policy')
    op.drop_table('shipping_policy_mapping')
    # ### end Alembic commands ###
