"""empty message

Revision ID: e3e99e2ff1b1
Revises: 5b84e26fadeb
Create Date: 2021-03-09 11:34:11.909944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
from sqlalchemy.orm import Session

revision = 'e3e99e2ff1b1'
down_revision = '5b84e26fadeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result_imports',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, primary_key=True),
                    sa.Column('import_id', sa.Integer(), nullable=True, index=True),
                    sa.Column('data', sa.JSON(), nullable=True),
                    sa.Column('output', sa.JSON(), nullable=True),
                    sa.Column('status', sa.String(length=30), nullable=True),
                    sa.Column('message', sa.String(length=255), nullable=True),
                    sa.Column('tag', sa.String(length=32), nullable=True),
                    sa.Column('product_id', sa.Integer(), nullable=True),
                    sa.Column('created_by', sa.String(100), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_by', sa.String(100), nullable=True, index=True),
                    sa.Column(
                        'updated_at',
                        sa.TIMESTAMP(),
                        server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
                        nullable=False
                    ))
    bind = op.get_bind()
    sesssion = Session(bind=bind)
    update_misc_sql = """
                        INSERT INTO misc (`name`, `type`, `code`) 
                        VALUES 
                        ('Thêm mới sản phẩm - đăng tải thông tin cơ bản', 'import_type', 'create_product_basic_info')
                        """
    sesssion.execute(update_misc_sql)
    sesssion.commit()


def downgrade():
    op.drop_table('result_imports')
    bind = op.get_bind()
    sesssion = Session(bind=bind)
    update_misc_sql = """
                        DELETE FROM misc WHERE `type` = 'import_type' AND `code` = 'create_product_basic_info'
                        """
    sesssion.execute(update_misc_sql)
    sesssion.commit()