"""run migration product_details_v2

Revision ID: e5c1b70eeffe
Revises: 744537188ede
Create Date: 2021-08-27 14:12:10.362749

"""
import os
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import mysql
from catalog import config

# revision identifiers, used by Alembic.
revision = 'e5c1b70eeffe'
down_revision = '744537188ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with open(os.path.join(config.ROOT_DIR, 'catalog', 'utils', 'MIGRATE_PRODUCT_DETAILS_V2.sql'), 'r') as file:
        sql = file.read()
        op.execute(text(sql))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
