"""Add new import type

Revision ID: f7ba81939ad6
Revises: 1807143a0d05
Create Date: 2022-01-23 22:29:16.699294

"""
from alembic import op
from sqlalchemy import text
from sqlalchemy.orm import Session

# revision identifiers, used by Alembic.
revision = 'f7ba81939ad6'
down_revision = '1807143a0d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    bind = op.get_bind()
    session = Session(bind=bind)
    session.execute(
        text(
            """
            INSERT INTO misc (`name`, `type`, `code`) 
            VALUES 
            ('Đăng tải nhanh sản phẩm', 'import_type', 'create_product_quickly')
            """
        )
    )
    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    bind = op.get_bind()
    session = Session(bind=bind)
    update_misc_sql = """
                        DELETE FROM misc WHERE `type` = 'import_type' AND `code` = 'create_product_quickly'
                        """
    session.execute(update_misc_sql)
    session.commit()
    # ### end Alembic commands ###