"""empty message

Revision ID: f9fa2fdad980
Revises: 971c614677d0
Create Date: 2021-12-17 16:12:07.519777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9fa2fdad980'
down_revision = '971c614677d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attribute_options', 'priority',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attribute_options', 'priority',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
