# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: category.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='category.proto',
  package='catalog.category',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x63\x61tegory.proto\x12\x10\x63\x61talog.category\"\xce\x02\n\x0f\x43\x61tegoryMessage\x12\x0c\n\x04\x66\x65Id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\x12\x0e\n\x06parent\x18\x04 \x01(\r\x12\x10\n\x08sellerId\x18\x05 \x01(\r\x12\x10\n\x08isActive\x18\x06 \x01(\x08\x12\x11\n\ttaxInCode\x18\x07 \x01(\t\x12\x12\n\ntaxOutCode\x18\x08 \x01(\t\x12\x15\n\rincomeAccount\x18\t \x01(\t\x12\x1d\n\x15internalIncomeAccount\x18\n \x01(\t\x12\x10\n\x08tracking\x18\x0b \x01(\t\x12\x1d\n\x15stockValuationAccount\x18\x0c \x01(\t\x12\x12\n\nsaleBranch\x18\r \x01(\t\x12\x16\n\x0e\x65xpenseAccount\x18\x0e \x01(\t\x12\x15\n\rreturnAccount\x18\x0f \x01(\t\x12\x0c\n\x04path\x18\x10 \x01(\tb\x06proto3')
)




_CATEGORYMESSAGE = _descriptor.Descriptor(
  name='CategoryMessage',
  full_name='catalog.category.CategoryMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feId', full_name='catalog.category.CategoryMessage.feId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='catalog.category.CategoryMessage.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='catalog.category.CategoryMessage.code', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parent', full_name='catalog.category.CategoryMessage.parent', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sellerId', full_name='catalog.category.CategoryMessage.sellerId', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isActive', full_name='catalog.category.CategoryMessage.isActive', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='taxInCode', full_name='catalog.category.CategoryMessage.taxInCode', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='taxOutCode', full_name='catalog.category.CategoryMessage.taxOutCode', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='incomeAccount', full_name='catalog.category.CategoryMessage.incomeAccount', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='internalIncomeAccount', full_name='catalog.category.CategoryMessage.internalIncomeAccount', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tracking', full_name='catalog.category.CategoryMessage.tracking', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stockValuationAccount', full_name='catalog.category.CategoryMessage.stockValuationAccount', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='saleBranch', full_name='catalog.category.CategoryMessage.saleBranch', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expenseAccount', full_name='catalog.category.CategoryMessage.expenseAccount', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='returnAccount', full_name='catalog.category.CategoryMessage.returnAccount', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='catalog.category.CategoryMessage.path', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=371,
)

DESCRIPTOR.message_types_by_name['CategoryMessage'] = _CATEGORYMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CategoryMessage = _reflection.GeneratedProtocolMessageType('CategoryMessage', (_message.Message,), dict(
  DESCRIPTOR = _CATEGORYMESSAGE,
  __module__ = 'category_pb2'
  # @@protoc_insertion_point(class_scope:catalog.category.CategoryMessage)
  ))
_sym_db.RegisterMessage(CategoryMessage)


# @@protoc_insertion_point(module_scope)
