# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sellable_update.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sellable_update.proto',
  package='catalog.sellable',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15sellable_update.proto\x12\x10\x63\x61talog.sellable\"\xac\x04\n\x15SellableUpdateMessage\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x11\n\tuomPoCode\x18\x02 \x01(\t\x12\x12\n\npartNumber\x18\x03 \x01(\t\x12\x0f\n\x07\x62\x61rcode\x18\x04 \x01(\t\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x0f\n\x07uomCode\x18\x06 \x01(\t\x12\x0c\n\x04type\x18\x07 \x01(\t\x12\x10\n\x08isActive\x18\x08 \x01(\x08\x12\x11\n\tcategCode\x18\t \x01(\t\x12\x15\n\rcostPriceCalc\x18\n \x01(\x08\x12\x11\n\tvatInCode\x18\x0c \x01(\t\x12\x16\n\x0ewarrantyPeriod\x18\r \x01(\x02\x12\x14\n\x0cwarrantyNote\x18\x0e \x01(\t\x12\x18\n\x10productBrandCode\x18\x0f \x01(\t\x12\x19\n\x11\x64\x61ysBeforeExpLock\x18\x10 \x01(\r\x12\x0e\n\x06weight\x18\x11 \x01(\r\x12\x0e\n\x06length\x18\x12 \x01(\r\x12\r\n\x05width\x18\x13 \x01(\r\x12\x0e\n\x06height\x18\x14 \x01(\r\x12\x10\n\x08sellerId\x18\x15 \x01(\r\x12\x16\n\x0eserialTracking\x18\x16 \x01(\x08\x12\x1a\n\x12\x61utoGenerateSerial\x18\x17 \x01(\x08\x12\x10\n\x08sellable\x18\x18 \x01(\x08\x12\x16\n\x0e\x65xpiryTracking\x18\x19 \x01(\x08\x12\x16\n\x0e\x65xpirationType\x18\x0b \x01(\r\x12\x11\n\tsellerSku\x18\x1a \x01(\t\x12\x15\n\rshippingTypes\x18\x1b \x03(\tb\x06proto3')
)




_SELLABLEUPDATEMESSAGE = _descriptor.Descriptor(
  name='SellableUpdateMessage',
  full_name='catalog.sellable.SellableUpdateMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sku', full_name='catalog.sellable.SellableUpdateMessage.sku', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uomPoCode', full_name='catalog.sellable.SellableUpdateMessage.uomPoCode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='partNumber', full_name='catalog.sellable.SellableUpdateMessage.partNumber', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='barcode', full_name='catalog.sellable.SellableUpdateMessage.barcode', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='catalog.sellable.SellableUpdateMessage.name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uomCode', full_name='catalog.sellable.SellableUpdateMessage.uomCode', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='catalog.sellable.SellableUpdateMessage.type', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isActive', full_name='catalog.sellable.SellableUpdateMessage.isActive', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='categCode', full_name='catalog.sellable.SellableUpdateMessage.categCode', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='costPriceCalc', full_name='catalog.sellable.SellableUpdateMessage.costPriceCalc', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vatInCode', full_name='catalog.sellable.SellableUpdateMessage.vatInCode', index=10,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='warrantyPeriod', full_name='catalog.sellable.SellableUpdateMessage.warrantyPeriod', index=11,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='warrantyNote', full_name='catalog.sellable.SellableUpdateMessage.warrantyNote', index=12,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='productBrandCode', full_name='catalog.sellable.SellableUpdateMessage.productBrandCode', index=13,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='daysBeforeExpLock', full_name='catalog.sellable.SellableUpdateMessage.daysBeforeExpLock', index=14,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weight', full_name='catalog.sellable.SellableUpdateMessage.weight', index=15,
      number=17, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length', full_name='catalog.sellable.SellableUpdateMessage.length', index=16,
      number=18, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='catalog.sellable.SellableUpdateMessage.width', index=17,
      number=19, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='catalog.sellable.SellableUpdateMessage.height', index=18,
      number=20, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sellerId', full_name='catalog.sellable.SellableUpdateMessage.sellerId', index=19,
      number=21, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serialTracking', full_name='catalog.sellable.SellableUpdateMessage.serialTracking', index=20,
      number=22, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='autoGenerateSerial', full_name='catalog.sellable.SellableUpdateMessage.autoGenerateSerial', index=21,
      number=23, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sellable', full_name='catalog.sellable.SellableUpdateMessage.sellable', index=22,
      number=24, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expiryTracking', full_name='catalog.sellable.SellableUpdateMessage.expiryTracking', index=23,
      number=25, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expirationType', full_name='catalog.sellable.SellableUpdateMessage.expirationType', index=24,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sellerSku', full_name='catalog.sellable.SellableUpdateMessage.sellerSku', index=25,
      number=26, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shippingTypes', full_name='catalog.sellable.SellableUpdateMessage.shippingTypes', index=26,
      number=27, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=600,
)

DESCRIPTOR.message_types_by_name['SellableUpdateMessage'] = _SELLABLEUPDATEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SellableUpdateMessage = _reflection.GeneratedProtocolMessageType('SellableUpdateMessage', (_message.Message,), dict(
  DESCRIPTOR = _SELLABLEUPDATEMESSAGE,
  __module__ = 'sellable_update_pb2'
  # @@protoc_insertion_point(class_scope:catalog.sellable.SellableUpdateMessage)
  ))
_sym_db.RegisterMessage(SellableUpdateMessage)


# @@protoc_insertion_point(module_scope)
